### ISSUE TITLE
Multiple function signatures are incorrectly marked as Entity<T> or AnyEntity instead of number

### ISSUE THREAD

**Issue by Reselim** [Ukendio/Matter#9]
`Entity<T>` *does* accept numbers, but it is not the correct signature for any of these

# QueryResult

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L124

https://eryn.io/matter/api/QueryResult#next

# Debugger

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/debugger/debugger.d.ts#L36

https://eryn.io/matter/api/Debugger#findInstanceFromEntity

# World

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L71

https://eryn.io/matter/api/World#despawn

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L77

https://eryn.io/matter/api/World#replace

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L81

https://eryn.io/matter/api/World#contains

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L83

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L88

https://eryn.io/matter/api/World#get

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L101

https://eryn.io/matter/api/World#insert

https://github.com/Ukendio/Matter/blob/c43a2a95b32e8f21efcd087dd15166ab3878e6db/lib/World.d.ts#L103

https://eryn.io/matter/api/World#remove

**Comment by LastTalon** [comment]
It looks like all these places are supposed to use entities. The typings provide nominal entities rather than structural entities (plain numbers) to prevent accidental misuse. You can also cast them back and forth if the need arises and this forces the developer to consider that they really mean to be using a number in place of an entity and vice versa.

This is similar to roblox-ts's LuaTuple type which is also made nominal for the same and other similar reasons. You want the developer to consider when using them in place of one another.

**Comment by Ukendio** [comment]
@LastTalon is entirely correct in the motivation for these types, however I recognize that this issue stems from poor documentation which is entirely my fault and I have now tried to add some documentation to reflect this information along with other stuff in the most recent commit 9ae904c5a238e6c3da6c91086c258fca2b53d5de. 

I am going to close this issue in a few days unless there are any further comments regarding whether we *should* have nominal types for entities. We should treat them as plain numbers but I see value in upholding a type contract that ensures some safety when using them.

**Comment by Reselim** [comment]
Got it. Feel free to close whenever.
